### ISSUE TITLE
Explore Transcripts Content Page

### ISSUE THREAD

**Issue by Emmanuel-Develops** [bitcointranscripts/registry#17]
### Components:
- [ ] Main content page
<img width="1117" alt="Screenshot 2024-09-09 at 11 07 26 AM" src="https://github.com/user-attachments/assets/850a57ad-4363-40f4-a9f0-f6fff5daf6f7">

- [ ] Navigation component for main content page
There are two distinct components for navigating the main content page
<img width="223" alt="Screenshot 2024-09-09 at 11 07 48 AM" src="https://github.com/user-attachments/assets/8c625288-c2ba-4b16-9c79-39e6e4e744f0"><img width="223" alt="Screenshot 2024-09-09 at 11 07 56 AM" src="https://github.com/user-attachments/assets/90d1d9c7-3a53-4202-94d9-cc05366af4e7">

These two sections (main content page and navigation component) covers all the possible routes under explore section. Namely `Categories`, `Topics`, `Types`, `Speakers`, and `Sources`.
Data is available for `Types` and `Speakers` which will be built first.

**Comment by kouloumos** [comment]
This is done
