### ISSUE TITLE
GIF troubles

### ISSUE THREAD

**Issue by Emmanuel-Develops** [bitcointranscripts/registry#25]
The current gif file is about 11MB, definitely too large to be used on the landing page.

Follow this discussion for more context:
https://github.com/bitcointranscripts/registry/pull/22#pullrequestreview-2299489014

I have reduced the the video length to 3 seconds and removed audio from the clip. Size is 469KB

Here is the output: 

https://github.com/user-attachments/assets/c5176826-ab31-4b6f-a128-28887c2c14a5

cc: @kouloumos @IgboPharaoh

**Comment by kouloumos** [comment]
nice work @Emmanuel-Develops! Could you also provide the file sizes for longer versions of the clip with the same setup? Specifically, could you try it for 10 seconds and the full length? Thanks!

**Comment by Emmanuel-Develops** [comment]
> nice work @Emmanuel-Develops! Could you also provide the file sizes for longer versions of the clip with the same setup? Specifically, could you try it for 10 seconds and the full length? Thanks!

Yeah sure, but for what needs specifically? The ~4 seconds one runs well on the browser and loops indefinitely (like a GIF). Also very small file size of 469kb. 
Is there a specific reason for a longer version?
cc: @kouloumos
