### ISSUE TITLE
Transcript Aliases

### ISSUE THREAD

**Issue by Emmanuel-Develops** [bitcointranscripts/registry#32]
Some transcripts have aliases (other transcript paths that reference to them).

For example take this [transcript](https://github.com/bitcointranscripts/bitcointranscripts/blob/master/bitcoin-explained/rsk-federated-sidechains-and-powpeg.md).

In its metadata, it has an aliases key of `['/bitcoin-magazine/bitcoin-explained/rsk-federated-sidechains-and-powpeg']`.
This means this path in aliases should redirect to itself as reference. 
I call it old-path for convenience. There could be multiple paths as aliases.
Basically old-path `/bitcoin-magazine/bitcoin-explained/rsk-federated-sidechains-and-powpeg` redirects to new-path `bitcoin-explained/rsk-federated-sidechains-and-powpeg.md`

This feature is missing in the new registry.

### Proposal.
Create a JOSN on build (contentlayer) pull all transcripts with aliases into an object, with the pattern `old-path` as key, and `new-path` as value
e.g 
```js
{ 'bitcoin-magazine/bitcoin-explained/rsk-federated-sidechains-and-powpeg': '
bitcoin-explained/rsk-federated-sidechains-and-powpeg', ... }
```
Then write a middleware to match the pattern.
i.e if a route matches a key (old-path) in this Aliases obj, redirect the request to the value (new-path).
else next()

**Comment by kouloumos** [comment]
this is fixed
