### ISSUE TITLE
Breadcrumb Titles

### ISSUE THREAD

**Issue by Emmanuel-Develops** [bitcointranscripts/registry#53]
### Breadcrumbs title
issue: Breadcrumbs should use the title of the source or transcript it is on.

Old registry breadcrumb below. notice the title (Bit Block Boom 2019)
<img width="585" alt="Screenshot 2024-10-30 at 11 15 25 AM" src="https://github.com/user-attachments/assets/fb34bbfd-f492-4e05-818f-eea90eda6b6c">

new registry breadcrumb below (this should be fixed)
<img width="391" alt="Screenshot 2024-10-30 at 11 15 51 AM" src="https://github.com/user-attachments/assets/8603d172-260a-4479-af67-55c56618e991">

additional context: https://github.com/bitcointranscripts/registry/pull/51#issuecomment-2449624571

**Comment by kouloumos** [comment]
fixed
